"""Platformovo neutrálne jadro — nesmie importovať Freqtrade ani MultiCharts."""

from .clock import ClockState, SessionClock, SessionSpec, SessionWindow
from .config import CONFIG_DIR, ConfigError, IBSConfig, list_profiles, load_profile
from .drawing import (
    PAL,
    DrawBg,
    DrawBox,
    DrawCommand,
    DrawDelete,
    DrawKind,
    DrawLabel,
    DrawLine,
    DrawObject,
    DrawRegistry,
    DrawUpdate,
    LabelStyle,
    LineStyle,
    Palette,
)
from .engine import EngineOutput, IBSEngine
from .history import BarHistory
from .risk import TradePlan, TrailingPlan, build_trade_plan, swing_stop_loss
from .statemachine import (
    MarketContext,
    OrderAction,
    OrderIntent,
    StateEvent,
    StateMachine,
    ZoneState,
)
from .ta import ImbalanceHit, find_imbalance, is_engulfing, is_pin_bar
from .zones import Zone, ZoneBook, ZoneSource, SdPattern, detect_sd_pattern, snap_time
from .types import (
    BTCUSD_COINBASE,
    BTCUSDT_BINANCE,
    ETHUSDT_BINANCE,
    INSTRUMENTS,
    MNQ,
    Bar,
    Direction,
    HTFWindow,
    htf_window_opens,
    InstrumentSpec,
    OrderType,
    PanelPos,
    SizeSpec,
    SnapMode,
    TradeDirection,
)

__all__ = [
    "Bar",
    "HTFWindow",
    "htf_window_opens",
    "Direction",
    "TradeDirection",
    "SnapMode",
    "OrderType",
    "PanelPos",
    "SizeSpec",
    "InstrumentSpec",
    "MNQ",
    "BTCUSD_COINBASE",
    "BTCUSDT_BINANCE",
    "ETHUSDT_BINANCE",
    "INSTRUMENTS",
    "IBSConfig",
    "ConfigError",
    "CONFIG_DIR",
    "load_profile",
    "list_profiles",
    "SessionClock",
    "SessionSpec",
    "SessionWindow",
    "ClockState",
    "Palette",
    "PAL",
    "DrawKind",
    "DrawBox",
    "DrawLine",
    "DrawLabel",
    "DrawBg",
    "DrawCommand",
    "DrawDelete",
    "DrawObject",
    "DrawRegistry",
    "DrawUpdate",
    "LabelStyle",
    "LineStyle",
    "Zone",
    "ZoneBook",
    "ZoneSource",
    "SdPattern",
    "detect_sd_pattern",
    "snap_time",
    "BarHistory",
    "IBSEngine",
    "EngineOutput",
    "TradePlan",
    "TrailingPlan",
    "build_trade_plan",
    "swing_stop_loss",
    "ZoneState",
    "OrderAction",
    "OrderIntent",
    "StateEvent",
    "MarketContext",
    "StateMachine",
    "ImbalanceHit",
    "find_imbalance",
    "is_pin_bar",
    "is_engulfing",
]
